### ISSUE TITLE
0.1.5 errors out

### ISSUE THREAD

**Issue by jrhizor** [Moesif/moesifasgi#18]
@keyur9 it looks like https://github.com/Moesif/moesifasgi/pull/17 broke the library.

I was running into an error when trying to set up Moesif for the first time and was able to recreate it with the example project here:
```bash
git clone git@github.com:Moesif/moesifasgi.git
cd moesifasgi
cd examples/fastapi
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
python main.py
```

This errors with:
```
❯ python main.py
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/jrhzor/code/moesifasgi/examples/fastapi/env/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
Traceback (most recent call last):
  File "/Users/jrhzor/code/moesifasgi/examples/fastapi/main.py", line 233, in <module>
    app.add_middleware(MoesifMiddleware, settings=moesif_settings)
  File "/Users/jrhzor/code/moesifasgi/examples/fastapi/env/lib/python3.11/site-packages/starlette/applications.py", line 169, in add_middleware
    self.middleware_stack = self.build_middleware_stack()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrhzor/code/moesifasgi/examples/fastapi/env/lib/python3.11/site-packages/fastapi/applications.py", line 194, in build_middleware_stack
    app = cls(app=app, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrhzor/code/moesifasgi/examples/fastapi/env/lib/python3.11/site-packages/moesifasgi/middleware.py", line 59, in __init__
    self.event_queue_size = self.middleware_settings.get('EVENT_QUEUE_SIZE', 1000000)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MoesifMiddleware' object has no attribute 'middleware_settings'
```

I'm pretty sure it should just be `self.moesif_settings` instead of `self.middleware_settings`?

**Comment by keyur9** [comment]
Hello, @jrhizor! Sorry about the issue. We've fix the middleware and published the `moesifasgi` version. Please update to the latest version [pip install --no-cache moesifasgi](https://pypi.org/project/moesifasgi/) and let use know if you still see the issue.

**Comment by jrhizor** [comment]
Thanks! That was super fast! (and it fixed the issue)
